<script src="{{asset('public/Doctors/assets/js/vendor/modernizr-3.6.0.min.js')}}"></script>
<script src="{{asset('public/Doctors/assets/js/vendor/jquery-3.3.1.min.js')}}"></script>
<script src="{{asset('public/Doctors/assets/js/vendor/popper.min.js')}}"></script>
<script src="{{asset('public/Doctors/assets/js/vendor/bootstrap.min.js')}}"></script>
<!--Plugins JS-->
<script src="{{asset('public/Doctors/assets/js/plugins/perfect-scrollbar.min.js')}}"></script>
<script src="{{asset('public/Doctors/assets/js/plugins/tippy4.min.js.js')}}"></script>
<!--Main JS-->
<script src="{{asset('public/Doctors/assets/js/main.js')}}"></script>
